version: '3.8'

services:
  incidents-healthcheck-bot:
    build: .
    container_name: incidents-healthcheck-telegram-bot
    ports:
      - "8558:8558"
    env_file:
      - .env
    restart: unless-stopped
